package speciesselection;

/**
 *
 * @author mre16utu
 */
public class Constants {

    public static final String AREAS = "Areas";
    public static final String PRECISION = "Precision";
    public static final String NONE = "None";
    

    // Read Me file text to go in the about page
    private static final String TAB = "&emsp;";
    public static final String ABOUT
            = "<style> body {background-color: #D6D9DF;}</style>"
            + "<b>Species Selection Version 2.0</b> - a product of the University "
            + "of East Anglia, Norwich, England<br>"
            + "Software produced by:<br>"
            + "Taoyang Wu - Mar 2014 & Feb 2016<br>"
            + "Stephen Whiddett -  Jan 2018 - Last updated 29MAR18<br>"
            + "<br>"
            + "Note: Input files must be in same directory at SpeciesSelection.jar "
            + "and all output files are written to that same directory.<br>"
            + "<br>"
            + "<b>Process</b> - Use this tab for Species Selection. Various Process "
            + "Options are available. Please see the ReadMe file for details. "
            + "Option A performs standard Species Selection. There is an option to "
            + "truncate results. If selected, this will generate output until 3 "
            + "consecutive increases in minimum mean sensitivity are detected. No "
            + "truncation produces full results output.<br>"
            + "<br>"
            + "<b>Analyse</b> - This tab allows 'Problem Species' (PS), that cause "
            + "greater than exponential growth to the processing time of a Species "
            + "Selection dataset, to be identified. This is achieved by comparing "
            + "MinSpecSetFamily size to that predicted by an exponental curve fitted "
            + "to the previous data points. Initial No of Species should be set to a "
            + "value processing takes a short amount of time. Allowable % Exp divergence "
            + "should be low on an initial run but could be increased on subsequent "
            + "runs if too many PS are detected.<br>"
            + "<br>"
            + "<b>Probability</b> - Calculates the probability that each species will "
            + "appear in an optimal result set when a Species Selection dataset is "
            + "randomly sampled for subsets of the specified size and number. Truncation "
            + "is allowed and the number of min mean sensitivity increases required "
            + "prior to truncation can be specified. The default is 3. A probability "
            + "threshold is also provided. Species with a maximum probability of "
            + "inclusion below this threshold will be excluded from the subset of "
            + "species written out to 'filename'_ProbsSet.txt. The default is 0.1. "
            + "The option is available to overwrite that previous probabilities txt "
            + "file. If unselected, the user can specified a filename for the output. "
            + "Delete Files will remove subset and subset results files but will leave "
            + "the probabilities file alone. View Results will open that last saved "
            + "probabilities file in notepad.<br>"
            + "<br>"
            + "=================<br>"
            + "Detailed Explanation<br>"
            + "=================<br>"
            + "<br>"
//            + "Version 2.0, 2018-03-21<br>"
//            + "Developed by Taoyang Wu <taoyang.wu@uea.ac.uk> for an objective, "
//            + "niche-based approach to indicator species selection proposed by "
//            + "Simon Butler <Simon.J.Butler@uea.ac.uk> etc (see Ref 1 below).<br>"
//            + "Further developed by Stephen Whiddett <s.whiddett@uea.ac.uk> to "
//            + "add investigative functionality and a GUI.<br>"
//            + "<br>"
//            + "**********************************************************************************************<br>"
            + "The input of the program is a text file containing the information "
            + "for species and indicators. Columns 1 and 3 contain positive integer "
            + "values representing species and resources respectively. Columns 2 "
            + "and 4 contain positive integer or decimal values representing reliance "
            + "and sensitivity respectively. In an option C file, column 5 contains "
            + "positive integer or double values representing areas or precisions. "
            + "All subsequent column values must be 1 or 0 indicating whether the "
            + "species uses the resource (1 being positive).<br>"
            + "The first row of the file must contain column headers of the format "
            + "specifically defined below. Note that as of v2.0, naming species with "
            + "strings is not allowed.<br>"
            + "<br>"
            + "An example data input file for use with Options A or B might contain:<br>"
            + "Species"+TAB+"Reliance"+TAB+"Resources"+TAB+"Sensitivity"+TAB+"R1"+TAB+"R2"+TAB+"R3"+TAB+"R4"+TAB+"R5"+TAB+"R6<br>"
            + "1"+TAB+"3"+TAB+"6"+TAB+"18"+TAB+"1"+TAB+"1"+TAB+"1"+TAB+"1"+TAB+"1"+TAB+"1<br>"
            + "2"+TAB+"2"+TAB+"1"+TAB+" 2"+TAB+"1"+TAB+"0"+TAB+"0"+TAB+"0"+TAB+"1"+TAB+"0<br>"
            + "3"+TAB+"3"+TAB+"2"+TAB+" 6"+TAB+"0"+TAB+"0"+TAB+"1"+TAB+"1"+TAB+"0"+TAB+"1<br>"
            + "4"+TAB+"3"+TAB+"2"+TAB+"16"+TAB+"0"+TAB+"1"+TAB+"1"+TAB+"1"+TAB+"0"+TAB+"0<br>"
            + "5"+TAB+"3"+TAB+"2"+TAB+" 6"+TAB+"0"+TAB+"0"+TAB+"1"+TAB+"1"+TAB+"0"+TAB+"1<br>"
            + "6"+TAB+"3"+TAB+"2"+TAB+"16"+TAB+"0"+TAB+"1"+TAB+"1"+TAB+"1"+TAB+"0"+TAB+"0<br>"
            + "...<br>"
            + "<br>"
            + "An example data input file for use with Option C might contain:<br>"
            + "Species"+TAB+"Reliance"+TAB+"Resources"+TAB+"Sensitivity"+TAB+"Area"+TAB+"R1"+TAB+"R2"+TAB+"R3"+TAB+"R4"+TAB+"R5"+TAB+"R6<br>"
            + "1"+TAB+"3"+TAB+"6"+TAB+"18"+TAB+"60000"+TAB+"1"+TAB+"1"+TAB+"1"+TAB+"1"+TAB+"1"+TAB+"1<br>"
            + "2"+TAB+"2"+TAB+"1"+TAB+" 2"+TAB+" 5000"+TAB+"1"+TAB+"0"+TAB+"0"+TAB+"0"+TAB+"1"+TAB+"0<br>"
            + "3"+TAB+"3"+TAB+"2"+TAB+" 6"+TAB+"20000"+TAB+"0"+TAB+"0"+TAB+"1"+TAB+"1"+TAB+"0"+TAB+"1<br>"
            + "4"+TAB+"3"+TAB+"2"+TAB+"16"+TAB+" 8000"+TAB+"0"+TAB+"1"+TAB+"1"+TAB+"1"+TAB+"0"+TAB+"0<br>"
            + "5"+TAB+"3"+TAB+"2"+TAB+" 6"+TAB+"20000"+TAB+"0"+TAB+"0"+TAB+"1"+TAB+"1"+TAB+"0"+TAB+"1<br>"
            + "6"+TAB+"3"+TAB+"2"+TAB+"16"+TAB+" 8000"+TAB+"0"+TAB+"1"+TAB+"1"+TAB+"1"+TAB+"0"+TAB+"0<br>"
            + "...<br>"
            + "<br>"
            + "Data input files should only be used where the header line contains the following title formats:<br>"
            + "Species	Reliance Resources Sensitivity R1 R2 R3 R4 R5 ... Rn			(Option A or B only)<br>"
            + "Species	Reliance Resources Sensitivity Area R1 R2 R3 R4 R6 ... Rn		(Option C only)<br>"
            + "Species	Reliance Resources Sensitivity Precision R1 R2 R3 R4 R6 ... Rn	(Option C only)<br>"
            + "<br>"
            + "Each row of data should contain integers only and have the same number of integer values as there are header strings.<br>"
            + "Species numbers should never repeat but need not be sequential.<br>"
            + "All indicators of resource usage must be a 1 or 0.<br>"
            + "<br>"
            + "The output is written to a text file named 'inputFileName_result.txt' "
            + "where 'inputFileName' is the name of the file containing the processed "
            + "data. For each size, that is, the number of species a species set "
            + "may have, a collection of optimal (and suboptimal) species sets are "
            + "given, in which the species sets are ordered by the maximal sensitivity "
            + "followed by average sensitivity. For each species set, the maximal "
            + "sensitivity and average sensitivity are also presented. For instance, "
            + "an output 105:57.00:[2, 5] represents a species set consisting of "
            + "two species, 2 and 5, with maximal sensitivity being 105 and average "
            + "sensitivity being 57. <br>"
            + "<br>"
            + "To run the program, double click on the file \"SpeciesSelection.jar\". "
            + "This will launch the GUI.<br>"
            + "<br>"
            + "**********************************************************************************************<br>"
            + "<br>"
            + "The 'Process' tab enables use of the features that were available "
            + "in previous versions of the software. <br>"
            + "Process option A processes the full dataset by the standard method "
            + "developed in Ref 1. The 'truncate results' option allows early "
            + "termination of the results output at a point where the minimum mean "
            + "sensitivity has increased in 3 consecutive result set sizes.<br>"
            + "<br>"
            + "Option B enables processing using trait based exclusion criteria. "
            + "Values for Species Threshold, 'm', and SD Threshold, 'x', may be set. "
            + "Values of zero are ignored.<br>"
            + "Value set for 'm' ---> Uses trait based exclusion criteria, where "
            + "traits used by less than m species are excluded. Here m is an integer<br>"
            + "Value set for 'x' ---> Uses trait based exclusion criteria, where "
            + "traits that are greater than x standard deviations from the average "
            + "community sensitivity are excluded. Here x is a decimal number.<br>"
            + "Value set for 'm' and 'x' ---> Uses trait based exclusion criteria, "
            + "where traits that are used by less than m species AND are greater "
            + "than x standard deviations from the average community sensitivity "
            + "are excluded.<br>"
            + "<br>"
            + "Option BF will use an imposed sensitivity.<br>"
            + "Option BN will use the normalised sensitivity.<br>"
            + "Option BFN will use a normalised imposed sensitivity, while still "
            + "applying values set for 'm' and/or 'x'.<br>"
            + "<br>"
            + "Option C enables use of area OR precision based criteria, where "
            + "species with area <b>less</b> than, or precision <b>greater</b> than Area/Prec Threshold, 'y', "
            + "are excluded. Here 'y' is a decimal number.<br>"
            + "Note here that the input file needs one additional column to specify "
            + "areas (or precision), see the file \"testAreas.txt\" included.<br>"
            + "Using option C will first exclude the species with area less than 'y', "
            + "and then use trait based exclusion criteria according to values set "
            + "for 'm' and 'x'.<br>"
            + "Options 'CN', 'CF' or \"CFN\" can be used for imposed/normalised "
            + "sensitivity as before.<br>"
            + "<br>"
            + "**********************************************************************************************<br>"
            + "<br>"
            + "The 'Analyse' tab is for use in identification of species in a dataset "
            + "that cause greater than exponential growth in the processing time "
            + "for a dataset, as each species is added to the dataset 1 by 1. The "
            + "initial number of species to use, 'n', must be specified. 'n' should "
            + "usually be set to a value where the initial subset is processed in no "
            + "more than a few seconds. Allowable % Exp divergence must also be set. "
            + "It is recommended that this value is set to a low value, such as 1, for "
            + "an initial run, and is then increased for subsequent runs if too many "
            + "marginally 'problem species' are identified.<br>"
            + "After clicking 'Find Problem Species', a subset of the first 'n' species "
            + "in the dataset will be processed and the MinSpecSetFamily (MSSF) size "
            + "is recorded. The next species in the dataset is added to the subset and "
            + "processed to again record MSSF size. An exponential curve is fitted to "
            + "the data points at each step (after the first 3 subsets have been processed) "
            + "which allows prediction of MSSF size when a subsequent species is added "
            + "to the dataset. Should actual MSSF size be greater than "
            + "(((100 + allowable % exp divergence)/100) * predicted MSSF size), the "
            + "species is identified as a 'problem species' and left out of subsequent "
            + "subsets. This expediates processing and results in a list of species "
            + "that may make processing of the full dataset impractical.<br>"
            + "Output may be produced for none, all or just the final subset to be run. "
            + "Outputting results is processing intensive and so it is recommended to "
            + "output results only where required by selection of the appropriate option.<br>"
            + "All processing on this tab uses option A.<br>"
            + "<br>"
            + "**********************************************************************************************<br>"
            + "<br>"
            + "The 'Probability' tab allows the processing of a specified number of "
            + "randomly generated subsets from an input dataset to be processed. All "
            + "subsets must match the resource coverage (universe) of the full dataset, "
            + "so specifying a subset size that is too low may mean that subsets "
            + "cannot be found or take too long to find. If 'Max Time' is exceeded "
            + "during subset generation, the program will abort and output the subsets "
            + "found so far. The generated subsets may be run.<br>"
            + "Truncation may be used, as in the Process tab, but the truncation threshold "
            + "(number of min mean sensitivity increases) may be specified. A probability "
            + "threshold may also be specified.<br>"
            + "Running the subsets allows generation of output that identifies the "
            + "probability that a species will appear in an optimal result set, of "
            + "each set size, and therefore allows identification of species that "
            + "never appear in an optimal solution. Exclusion of those improbable "
            + "species may enable processing where it was previously impractical due "
            + "to the length of processing time of the full dataset.<br>"
            + "By default, the probabilities calculated are written out to 'probabilities.txt' "
            + "but unchecked the overwrite option allows a filename to be specified. "
            + "At the bottom of this output file will be a list of species with probability "
            + "of inclusion in an optimal result set greater than the probability threshold "
            + "specified.<br>"
            + "A second output file is produced named 'inputFileName_ProbsSet.txt' where "
            + "'inputFileName' is the name of the file containing the processed data. "
            + "This file contains the subset of species identified above ready for "
            + "subsequent processing.<br>"
            + "All processing on this tab option A.<br>"
            + "<br>"
            + "**********************************************************************************************<br>"
            + "<br>"
            + "Ref 1: Wade, A.S.I,  Barov, B.,  Burfield, I.J.,  Gregory, R.D.,  "
            + "Norris, K., Wu, T., and Butler S.J. (2014) A niche-based framework "
            + "to assess current monitoring of European forest birds and guide indicator "
            + "species' selection.<br>"
            + "PLoS One, 9(5): e97217 <br>"
            + "<br>"
            + "Ref 2: \"An objective, niche-based approach to indicator species "
            + "selection\" by Simon J. Butler etc. in \"Methods in Ecology and "
            + "Evolution\" 2012. ";
}
